language: python
dist: trusty
sudo: required
matrix:
  include:
    - os: linux
      sudo: required
      python: 2.7
    - os: linux
      sudo: required
      python: 3.4
    - os: linux
      sudo: required
      python: 3.5
    - os: linux
      sudo: required
      python: 3.6
    - os: osx
before_install:
  - ./.travis/before_install.sh
install:
  - pip install -e .
script:
  - pytest --cov
after_success:
  - codecov
notifications:
  slack: climate-models:LuGwA2dGrgZRL1O7AssggqyP
